language: node_js

node_js:
  - "stable"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run lint
  - npm run test:coverage

after_success:
  - npm run report-coverage
